import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
def read(path): return (ROOT / path).read_text(encoding='utf-8')

class BrandFirstExploreContract(unittest.TestCase):
    def test_header_and_explore_hierarchy(self):
        header=read('src/components/Header.astro')
        explore=read('src/data/explore.ts')
        self.assertEqual(header.count('Wall Art <span class="nav-caret"'),2)
        self.assertEqual(header.count('Shop <span class="nav-caret"'),2)
        self.assertEqual(header.count('Explore <span class="nav-caret"'),2)
        self.assertIn("['About', '/about/']",header)
        self.assertEqual(header.count('EXPLORE ALL'),2)
        self.assertEqual(header.count('class="nav-explore-grid"'),2)
        self.assertNotIn('nav-explore-title',header)
        self.assertNotIn('nav-explore-choice-details',header)
        self.assertIn('grid-template-columns: repeat(4, minmax(0, 1fr));',header)
        for title in ('Stories','Search & Rescue','Camping','Landforms','Trails','Maps & Guides','Current Conditions','Hiking Safety'):
            self.assertIn(f"title: '{title}'", explore)
        self.assertIn("target={link.external ? '_blank' : undefined}",header)
        self.assertNotIn('View All Stories',explore)
        self.assertNotIn('Kentucky Emergency Management - Search & Rescue',explore)
        self.assertIn("rel={link.external ? 'noopener noreferrer' : undefined}",header)

    def test_explore_page_and_story_routes(self):
        self.assertTrue((ROOT/'src/pages/explore.astro').exists())
        self.assertTrue((ROOT/'src/pages/stories/index.astro').exists())
        self.assertTrue((ROOT/'src/pages/stories/[slug].astro').exists())
        stories=read('src/data/stories.ts')
        self.assertEqual(stories.count("authorName: 'Ryan D. Lewis'"),1)
        for slug in ('lilis-leap','the-day-the-gorge-took-13-hours','the-blank-places-on-the-map','the-fletcher-ridge-hunt','granddaddys-arch','walking-home'):
            self.assertIn(f"id: '{slug}'",stories)
        stories_index=read('src/pages/stories/index.astro')
        self.assertIn('explore/#stories',stories_index)
        legacy=read('src/pages/exploring-the-gorge.astro')
        self.assertIn('canonicalPath="/explore/"',legacy)
        self.assertIn('window.location.replace',legacy)
        self.assertIn('explore/#stories',legacy)

    def test_creator_model_is_data_driven(self):
        products=read('src/data/products.ts')
        photo=read('src/pages/photographs/[slug].astro')
        artwork=read('src/components/Artwork.astro')
        for field in ('creatorName','creatorRole','copyrightHolder','copyrightNotice','storyAuthor'):
            self.assertIn(field,products)
        self.assertIn("creator: { '@type': 'Person', name: photo.creatorName }",photo)
        self.assertIn("copyrightHolder: { '@type': 'Person', name: photo.copyrightHolder }",photo)
        self.assertNotIn('<dt>Creator</dt>',photo)
        self.assertNotIn('<dt>Copyright holder</dt>',photo)
        self.assertNotIn('<dt>Medium</dt><dd>Photography</dd>',photo)
        self.assertNotIn('<dt>Creator role</dt>',photo)
        self.assertNotIn('<dt>Story author</dt>',photo)
        self.assertNotIn('creator-details',photo)
        self.assertNotIn('Photography by {photo.creatorName}',photo)
        self.assertNotIn('Story by {photo.storyAuthor}',photo)
        self.assertIn('Photograph {photo.copyrightNotice}',photo)
        self.assertNotIn('Photograph © Ryan D. Lewis. All rights reserved.',photo)
        self.assertIn("copyrightNotice: '© Ryan D. Lewis. All rights reserved.'",products)
        self.assertNotIn('Photography by Ryan D. Lewis</figcaption>',artwork)
        card=read('src/components/Card.astro')
        self.assertNotIn('card-creator',card)
        stories=read('src/data/stories.ts')
        self.assertIn('paragraphPlans',stories)
        self.assertNotIn('placeholderPhotoSlug',stories)
        story_page=read('src/pages/stories/[slug].astro')
        self.assertNotIn('Related photograph',story_page)
        self.assertNotIn('All stories',story_page)
        self.assertNotIn('data-story-image-placeholder',story_page)
        self.assertNotIn("import Artwork from",story_page)
        self.assertIn('search-and-rescue/#hiking-safety',story_page)
        explore=read('src/data/explore.ts')
        self.assertIn('search-and-rescue/#hiking-safety',explore)
        self.assertIn("label: '2026 DBNF Dispersed Camping Guide Download'",explore)
        self.assertIn("href: '/downloads/red-river-gorge-hiker-2026-dbnf-dispersed-camping-guide.pdf', download: true",explore)
        self.assertNotIn("label: 'Download Guide'",explore)

    def test_brand_contact_footer_about_and_home_metadata(self):
        footer=read('src/components/Footer.astro')
        contact=read('src/pages/contact.astro')
        about=read('src/pages/about.astro')
        home=read('src/pages/index.astro')
        permissions=read('src/pages/photography-use-and-permissions.astro')
        self.assertIn('mailto:Info@RedRiverGorgeHiker.com',footer)
        self.assertIn('© Red River Gorge Hiker, LLC. All rights reserved.',footer)
        self.assertNotIn('Photographs © Ryan D. Lewis.',footer)
        self.assertIn('Info@RedRiverGorgeHiker.com',contact)
        self.assertIn('applicable copyright holder or authorized rights representative',permissions)
        self.assertNotIn("Ryan's story",about)
        self.assertIn('The goal is not to make one person the center of the story.',about)
        self.assertIn('It began with one hiker spending a lot of time exploring the Gorge, but it was never meant to stop there.',about)
        self.assertIn('The exploration came first. The photographs came from being out there.',about)
        self.assertIn('Red River Gorge Hiker, LLC maintains two separate commitments to Wolfe County Search &amp; Rescue: at least $500 each calendar year, plus 20% of positive Red River Gorge Hiker business profit.',about)
        explore_page=read('src/pages/explore.astro')
        self.assertIn('<h2>Take the Gorge with you</h2>',explore_page)
        self.assertIn('Explore photography and gear inspired by the same places, or see how Red River Gorge Hiker supports Wolfe County Search &amp; Rescue.',explore_page)
        self.assertIn('Red River Gorge Hiker | Explore the Gorge, Art & Gear',home)
        self.assertIn('Stories, gear, and original photography from the Red River Gorge.',home)
        self.assertNotIn('Stories, maps, trails, camping, safety, art, gear, and practical resources for exploring the Gorge.',home)
        self.assertIn('href={`${base}explore/`}>Explore the Gorge</a>',home)
        self.assertIn('href={`${base}photography/`}>Explore Art</a>',home)
        self.assertIn('href={`${base}gear/`}>Shop</a>',home)
        self.assertIn('Proudly supporting Wolfe County Search &amp; Rescue →',home)
        self.assertIn('<p class="eyebrow">Exploration &amp; Stories</p>',home)
        self.assertIn('<h2>Exploring the Gorge</h2>',home)
        self.assertIn('Field notes, trail stories, changing weather, waterfalls, maps, safety, and practical resources for exploring the Gorge.',home)
        self.assertIn('href={`${base}explore/`}>Explore All →</a>',home)
        self.assertNotIn('Stories from the Gorge',home)
        self.assertNotIn('Read the Stories',home)
        header=read('src/components/Header.astro')
        self.assertIn('.site-header .desktop-nav .nav-view-all-explore {',header)
        self.assertIn('display: flex;',header)
        self.assertIn('width: fit-content;',header)
        self.assertIn('margin-top: -1.75rem;',header)
        self.assertIn('.site-header .mobile-primary-nav .nav-view-all-explore {',header)
        self.assertIn('margin-top: 1rem;',header)
        home_css=read('src/styles/home-brand.css')
        self.assertIn('width: min(13rem, 100%);',home_css)
        self.assertIn('min-height: 2.45rem;',home_css)
        self.assertIn('padding-block: .5rem;',home_css)
        products=read('src/data/products.ts')
        self.assertIn('On July 19, 2025, Ryan camped near Eagle’s Point Buttress',products)
        self.assertNotIn('On July 19, 2025, I camped near Eagle’s Point Buttress',products)
        self.assertIn("Explore Kentucky's Red River Gorge with stories, maps, landforms, trails, camping, safety and search-and-rescue resources, plus photography, art and gear.",home)

    def test_copy_correction_pass_uses_natural_visitor_facing_punctuation(self):
        about=read('src/pages/about.astro')
        shipping=read('src/pages/shipping-and-returns.astro')
        stories=read('src/data/stories.ts')
        products=read('src/data/products.ts')
        merch=read('src/data/merchandise.ts')
        gear_catalog=read('src/data/gearCatalog.ts')
        explore=read('src/data/explore.ts')
        self.assertIn('a connection to a place—the trails',about)
        self.assertIn('gets into you—and why you keep coming back',about)
        self.assertIn('order-specific questions, including delivery, damage, returns, refunds, and transaction questions, should be directed',shipping)
        self.assertIn('Between Frenchburg and Hemlock Lodge lay the Red River Gorge—and <strong>31.87 miles</strong> of walking.',stories)
        self.assertIn('Men’s T-Shirt (Athletic Fit) — Chest Logo',merch)
        self.assertIn('Men’s T-Shirt (Athletic Fit) — Pocket Logo',merch)
        self.assertIn('Single Card: $6.25',gear_catalog)
        self.assertIn('Sizes below 2XL: $45',merch)
        self.assertIn('visitor information, rules, and trip-planning resources',explore)
        self.assertNotIn('opening across the clearing landscape',products)
        self.assertNotIn('opened a stronger look at the morning sky',products)

    def test_commerce_and_measurement_boundaries_are_not_reauthored(self):
        products=read('src/data/products.ts')
        self.assertEqual(products.count("wallArtUrl: 'https://store.redrivergorgehiker.com/"),6)
        self.assertEqual(products.count("puzzleUrl: 'https://store.redrivergorgehiker.com/"),3)
        analytics=read('src/components/AnalyticsConsent.astro')
        self.assertEqual(analytics.count("rkp('event', 'PAGE_VIEW')"),1)
        self.assertIn('loadRokuForUnitedStates',analytics)
        self.assertIn('G-HM48NST64P',analytics)
        self.assertIn('2613133188222',analytics)

if __name__ == '__main__':
    unittest.main()
